### ISSUE TITLE
Better changelog

### ISSUE THREAD

**Issue by mxnmnm** [CrimsonCrips/AlexsMobsInteraction#1]
Would it be possible to keep a proper changelog of the changes for each version? Are there any notable changes beyond getting turned into an addon instead of a fork? (also my discord account got disabled [waiting for appeal to bring it back -_-] so if you've pinged me and I haven't responded that's why)

**Comment by CrimsonCrips** [comment]
Yes i am very inconsistent in my changelog

I will refine it for future updates starting now
