### ISSUE TITLE
Errors in Entity Type Tags' Jsons

### ISSUE THREAD

**Issue by iBryguy** [CrimsonCrips/AlexsMobsInteraction#11]
I happened to have the Minecraft game output up while testing out mods, and found some errors being thrown related to tags from this mod. From what I've seen, they are almost entirely small typos. Not a difficult fix, from what I can see.  I've listed the ones I found.

- [Additional ',' at end of array in 'anaconda_targets.json'](https://github.com/CrimsonCrips/AlexsMobsInteraction/blob/dc7f7f40bd08d1492d94a8de5a91305ada48fc78/for%20datapack/data/alexsmobs/tags/entity_types/anaconda_targets.json#L77)
- [Additional ',' at end of array in 'snow_leopard_targets.json'](https://github.com/CrimsonCrips/AlexsMobsInteraction/blob/dc7f7f40bd08d1492d94a8de5a91305ada48fc78/for%20datapack/data/alexsmobs/tags/entity_types/snow_leopard_targets.json#L22)
- [Missing closing bracket ( "\]" ) to end array in 'snow_leopard_targets.json'](https://github.com/CrimsonCrips/AlexsMobsInteraction/blob/dc7f7f40bd08d1492d94a8de5a91305ada48fc78/for%20datapack/data/alexsmobs/tags/entity_types/snow_leopard_targets.json#L23)
- ["drop_bear" instead of "dropbear" in 'boneserpent_kill.json'](https://github.com/CrimsonCrips/AlexsMobsInteraction/blob/dc7f7f40bd08d1492d94a8de5a91305ada48fc78/src/main/resources/data/alexinteraction/tags/entity_types/boneserpent_kill.json#L7)
- ["minecraft:soul_vulture" instead of "alexsmobs:soul_vulture" in 'boneserpent_kill.json'](https://github.com/CrimsonCrips/AlexsMobsInteraction/blob/dc7f7f40bd08d1492d94a8de5a91305ada48fc78/src/main/resources/data/alexinteraction/tags/entity_types/boneserpent_kill.json#L10C5-L10C29)
- 'alexsmobs:turtle' in various files. 'alexsmobs:turtle' is nonexistent. Possibly meant to be 'alexsmobs:alligator_snapping_turtle'?

Hope this helps! I've been thoroughly enjoying the additional interactions from this mod; keep up the great work!

**Comment by CrimsonCrips** [comment]
Thanks

**Comment by jaidaken** [comment]
These issues seem to persist in current version.

**Comment by CrimsonCrips** [comment]
Oh god i forgot, 
yeah i fixed it now
it should be fixed in the upcoming versions

**Comment by CrimsonCrips** [comment]
I have not updated yet
