### ISSUE TITLE
Tamed Grizzly Bear Attacking Tamed Axolotl And Villagers

### ISSUE THREAD

**Issue by LeafMan201** [CrimsonCrips/AlexsMobsInteraction#13]
Hello. I do not know why this happened but my Tamed Grizzly Bear in one of my worlds with this mod installed is aggressive towards Villagers and Axolotls, showing behavior that I'm more used to seeing with Komodo Dragons.

Was this intentional, something that hasn't been refined, or a bug of some sort? I'd like an explanation please.

**Comment by CrimsonCrips** [comment]
It being aggrsive towards axolotls and villagers is intentional
but it attacking them when tamed is a mistake

that will be fixed soon.

**Comment by LeafMan201** [comment]
You've got it. Thank you.
