### ISSUE TITLE
Soul vultures not spawning.

### ISSUE THREAD

**Issue by LeonarthCG** [CrimsonCrips/AlexsMobsInteraction#17]
When this mod is installed, even with just Alex's Mobs and Citadel, soul vultures fail to spawn. They do not spawn naturally, nor can spawn eggs be used to spawn them.

Soul vultures spawn just fine on version 2.3 of the mod, but on 3.0 and above, they simply do not spawn.

**Comment by CrimsonCrips** [comment]
Issue fixed, Await next update
