### ISSUE TITLE
Crash With Iron's Spells and Spellbooks

### ISSUE THREAD

**Issue by Mi6kbuttface** [CrimsonCrips/AlexsMobsInteraction#18]
On Forge 1.20.1 Latest version of each mod, here is what the crash log says
[crash-2024-06-11_01.40.26-server.txt](https://github.com/user-attachments/files/15782789/crash-2024-06-11_01.40.26-server.txt)

**Comment by CrimsonCrips** [comment]
This has already been fixed
please reinstall AMI on your respected Mod browser
