### ISSUE TITLE
Seagulls not getting buffed when eating golden apples

### ISSUE THREAD

**Issue by mxnmnm** [CrimsonCrips/AlexsMobsInteraction#2]
No matter what config entry I put for seagulls getting buffed with golden apples, they just don't. I know it worked in previous versions but that was before it was turned into an addon, so I think something broke there.

**Comment by CrimsonCrips** [comment]
Hi 
have you tried resetting your config?

**Comment by mxnmnm** [comment]
Oh I should've probably done that lol let me test rn

**Comment by mxnmnm** [comment]
Still broken :/

**Comment by CrimsonCrips** [comment]
ill also add one for golden apples

**Comment by mxnmnm** [comment]
It still happens with enchanted golden apples...

**Comment by mxnmnm** [comment]
Ok so it looks like the config just does not work... idk why but none of the changes I do have registered

**Comment by CrimsonCrips** [comment]
hm.

**Comment by CrimsonCrips** [comment]
alr got it fixed for the next update
