### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by KuryKat** [CrimsonCrips/AlexsMobsInteraction#23]
Hello. This was sent earlier by a CurseForge user, they were crashing because of this mod, since I'm a CF helper I thought this could be useful to report back to you.

```
java.lang.NullPointerException: Cannot invoke "com.github.alexthe666.alexsmobs.entity.EntitySkelewag.m_217043_()" because "this.skelewag" is null
	at com.crimsoncrips.alexsmobsinteraction.goal.AMISkelewagCircleGoal.⋖init⋗:L42
```

[Latest Log](https://cfpaste.modularity.gg/paste/?content=768367574001778729_1252866516391825470&filename=message.txt&raw=false#7363)

[Crash Report](https://cfpaste.modularity.gg/paste/?content=768367574001778729_1252871968865124392&filename=message.txt&raw=false#5)

They said they were having this issue on world creation, they'd try to create the world then simply crash. I have no further details.

Removing (or disabling) ``AlexsMobsInteraction`` fixed the issue.

Have a great day and happy coding!

**Comment by CrimsonCrips** [comment]
have they updated the mod yet to 3.3.1

**Comment by KuryKat** [comment]
From the latest log, no, they were still using 3.2 with the ``alexsmobsinteraction-3.2-all.jar``

Sorry I didn't catch that there was a newer version

**Comment by KuryKat** [comment]
Tried to warn them of it, hopefully they'll see and download the latest version ^^

![image](https://github.com/CrimsonCrips/AlexsMobsInteraction/assets/57152799/f7b3ef8a-48fd-4512-9ebc-e9a17896e373)

**Comment by CrimsonCrips** [comment]
No worries
