### ISSUE TITLE
vanilla (and possibly also alex's) mob drop rates appear to be heavily increased

### ISSUE THREAD

**Issue by notandvm** [CrimsonCrips/AlexsMobsInteraction#24]
pretty much as it says in the title; mob drop rates appear to be super increased with this mod enabled

noticed when in creative cows were dropping far more beef/leather than normal - checked with rabbits and they drop a rabbit's foot pretty much 100% of the time, sometimes 2

not sure if intentional or not, but i'm assuming not given there's no indication of such anywhere

**Comment by CrimsonCrips** [comment]
that is supposed to apply only for the snow leopard

this will be fixed in the next update
