### ISSUE TITLE
spiders eating every bee found wild

### ISSUE THREAD

**Issue by mateus3c** [CrimsonCrips/AlexsMobsInteraction#3]
I dislike this fork making changes to vanilla mobs, after all, this is Alex Mobs and it would be better if nothing too crazy or too different from the original mob style were added. Spiders are eating everything, finding bees isnt already the most easy task ever, but now every beehive found doesnt have any bees alive because Spiders (one of the most common monsters in the game) will spawn next to beehives and kill them all.

**Comment by CrimsonCrips** [comment]
then disable spiders eating things
theres litteraly a config for every feature
named alexsmobsinteraction.toml
also its not a fork anymore
its an addon
