### ISSUE TITLE
Crash upon loading any alex's mobs

### ISSUE THREAD

**Issue by TheCanadianCactus** [CrimsonCrips/AlexsMobsInteraction#31]
alex's mobs got updated, and something must have changed behavior or something. please fix

**Comment by SaltSouls** [comment]
This seems to be a result of the latest changes made to alex's mobs. Likely the AI related ones where they have moved several mobs pathfinding/various other AI tasks to be multithreaded to help with performance.

**Comment by Reimnop** [comment]
This is due to a new Alex's Mobs update. [This PR](https://github.com/CrimsonCrips/AlexsMobsInteraction/pull/32) won't fix the crash, but it'll communicate the issue better (at least I hope lmao).

**Comment by SaltSouls** [comment]
Is there a reason there is no plan to fix this issue? Is this mod being abandoned?
