### ISSUE TITLE
ALex mobs 1.22.9

### ISSUE THREAD

**Issue by GauntAndreX8** [CrimsonCrips/AlexsMobsInteraction#34]
please update your mod,
I can't join or create a world when using this mod with the latest version updated from Alex's mobs

**Comment by acewins727** [comment]
can confirm, incompatibility causes the game to crash on world join/render

**Comment by X66Herobrine66X** [comment]
+1

**Comment by CrimsonCrips** [comment]
it is being worked on in the bg
