### ISSUE TITLE
Not an issue or a suggestion, just wanted to give my feedback and tell you that you are KILLING it!

### ISSUE THREAD

**Issue by X66Herobrine66X** [CrimsonCrips/AlexsMobsInteraction#36]
I really like the new update, the textures in the book are very well made. I do have a list of feedback to give for constructive criticism.

- Love that devils hole pupfish can now be traded with villagers.
- Like that crimson mosquitos can be turned into warped moscos.
- Regarding the Skreech your last effect, it can be made very overpowered when combined with Amendments, which allows potion mixing in cauldrons. Basically you can dilute the effect until it lasts a single second and you have yourself an instant warden. ~~Also I think it too OP for splash potions, as you can get a bunch of mobs and spawn two dozen wardens. So perhaps limit the wardens to 1 per splash potion somehow?~~ Nevermind, just read the changelog to see that its only for players now, good job!
- Straddlers have an error in their translation file. The text of Straddler Ammo is copied to Straddler Vengeance.
- Really like Lasting Trust for Tusklins.
- I'm confused as to why there's two types of books for the guide, why do you need to craft it to make it work?

Really good update!

**Comment by CrimsonCrips** [comment]
Thank you, and i have now improved the Book
