### ISSUE TITLE
Ticking entities are causing multiple crashes on our server.

### ISSUE THREAD

**Issue by X66Herobrine66X** [CrimsonCrips/AlexsMobsInteraction#37]
[crash-2024-10-06_21.56.31-server.txt](https://github.com/user-attachments/files/17271022/crash-2024-10-06_21.56.31-server.txt)
[crash-2024-10-04_18.10.54-server.txt](https://github.com/user-attachments/files/17271026/crash-2024-10-04_18.10.54-server.txt)

First one has to do with crimson mosquitos, second one has to do with whales. I've had to delete region file multiple times :/,

**Comment by CrimsonCrips** [comment]
Give your modlist

**Comment by X66Herobrine66X** [comment]
https://drive.google.com/file/d/1Zt940-LJC5r4vqNoSLqbNINj3Dusjv5n/view

**Comment by CrimsonCrips** [comment]
something from your fabric mods is causing an issue, and therefore will not fix

**Comment by CrimsonCrips** [comment]
and also i advice you take up this issue with sinytra connector, not with me https://github.com/Sinytra/Connector/issues

**Comment by CrimsonCrips** [comment]
my bad, so one of the issues is by sinytra and another is with my code, the one with my fault should be fixed now but still talk to the sinytra devs about their side of the issue https://github.com/Sinytra/Connector/issues
