### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by ahowell610** [CrimsonCrips/AlexsMobsInteraction#38]
First of all, I love the mod. I would like to make a few suggestions for features

1.) Make it so Crocodiles no longer death roll their owner or any other entity on the owners team

2.) Make new mobs tameable. There are so many cool mobs that cannot currently be tamed and could just have the same ai goals that other mobs have. For example, the snow leopard could just copy the bears ai goals that have anything to do with taming and attacking. 

Here are a few mobs I think would be so cool to be able to tame:
- Soul Vulture (could use tarantula hawk ai)
- Snow Leopard (bear ai)
- Bison (elephant ai)
- Emu (kangaroo ai)
- Rhino (elephant ai)
- Moose (elephant ai)

Even if you didn't give them explicit ways to tame them, just having the functionality would be amazing for modpack makers (which is what I am doing). Then it would be possible to summon them already tamed.

**Comment by CrimsonCrips** [comment]
1. Crocodiles cant death roll their owner if they cant even attack their owner (and its also unrealistic for the crocodile to not attack other animals just cus they too are tamed by the same owner)

2.No thats not possible
