### ISSUE TITLE
[Suggestion] Give Lobsters a breeding item

### ISSUE THREAD

**Issue by Cephelo** [CrimsonCrips/AlexsMobsInteraction#39]
I know a lot of people would love to have lobsters as a farmable food source, though oddly enough they cannot be bred together.  I'm not sure how difficult this would be to implement though, so no pressure.  Fantastic work on this mod!

**Comment by X66Herobrine66X** [comment]
Wait you can't breed them? Then how tf are you supposed to get the rare colors? This should be in the base mod, so I'm going to agree with this.

**Comment by CrimsonCrips** [comment]
They cant be breeded in the base game

**Comment by X66Herobrine66X** [comment]
> They cant be breeded in the base game
Yea... that's why we want to be able to.

**Comment by CrimsonCrips** [comment]
no, i cannot do that
