### ISSUE TITLE
Can't fish

### ISSUE THREAD

**Issue by Ovan81** [CrimsonCrips/AlexsMobsInteraction#45]
Could not fish on server with this mod in our modpack, the bobber wouldnt cast out at all. we looked in the serverlogs to trace it back to the mod that caused it and it seems like the problem was this one, so if this is the case, hopefully this can get fixed so we can use it!
[message.txt](https://github.com/user-attachments/files/17556692/message.txt)

**Comment by CrimsonCrips** [comment]
this has been fixed

**Comment by CrimsonCrips** [comment]
await update

**Comment by Ovan81** [comment]
ty!
