### ISSUE TITLE
[FEATURE] Make Alex's Mobs optional

### ISSUE THREAD

**Issue by Reimnop** [CrimsonCrips/AlexsMobsInteraction#49]
I really like this mod but I don't wanna install Alex's Mobs, can you just add the mobs from Alex's Mobs into AMI? Thanks!

**Comment by CrimsonCrips** [comment]
nerd emoji

**Comment by Reimnop** [comment]
Any particular reason why you're not doing this? Is this mod abandoned

**Comment by mpustovoi** [comment]
> Any particular reason why you're not doing this? Is this mod abandoned

Read again what you are asking for.
At this point, just download Alex's Mobs and if you don't like some mobs, disable their spawning.

**Comment by CrimsonCrips** [comment]
thats my friend, it was satirical

**Comment by mpustovoi** [comment]
Well, I've seen comments like that in all seriousness.

**Comment by CrimsonCrips** [comment]
yeah i know where u were coming from

but no worries

**Comment by CrimsonCrips** [comment]
dumbass
