### ISSUE TITLE
[Question] Mod scope

### ISSUE THREAD

**Issue by zeid0ne** [CrimsonCrips/AlexsMobsInteraction#6]
I know the purpose of this mod is to add more interaction between Alexs mobs.
Is it also possible for it to improve Alexs mobs in other way ?

For example, by fixing bugs that Alex Mobs creator will not fix soon ? (https://github.com/AlexModGuy/AlexsMobs/issues/1842)
If yes that would be great !
If no, i'll close this issue so.

Thanks in all cases

**Comment by Reimnop** [comment]
Unfortunately fixing bugs of Alex's Mobs is not in the scope of this mod. If you can, I suggest forking Alex's Mobs to fix it yourself and merging your fix back into the base mod.
