### ISSUE TITLE
Latest update crashes Forge 47.2.18

### ISSUE THREAD

**Issue by hiide0us** [CrimsonCrips/AlexsMobsInteraction#8]
After a bit of troubleshooting (aka. deleting/reinstalling all my mods on curseforge to check for conflicts), turns out that the latest update causes modded minecraft 1.20.1 (+optifine ) to crash on launch! Just wanted to signal that :]

**Comment by CrimsonCrips** [comment]
its not from Opti
its just in my end

i released a new update that fixes it
